#ifndef CONFIG_H
#define CONFIG_H

#define LED_IR_PIN 15
#define BUILD_IN_LED 2
#define BUTTON_SEND_PIN 5
#define BUTTON_LEFT_PIN 25
#define BUTTON_MIDDLE_PIN 26
#define BUTTON_RIGHT_PIN 27

#define DEFAULT_CHNNL_MON 200
#define DEFAULT_CHNNL_THUS 201
#define DEFAULT_CHNNL_WEND 202
#define DEFAULT_CHNNL_THURS 203
#define DEFAULT_CHNNL_FRYD 204
#define DEFAULT_CHNNL_SAT 205
#define DEFAULT_CHNNL_SUN 206


#endif